[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
phases.setup.nixPkgs = ["python311", "pipenv"]
phases.install.cmds = [
  "cd backend && pip install -r requirements.txt"
]
phases.start.cmd = "cd backend/pharmacy && python manage.py runserver 0.0.0.0:$PORT"