[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["python"]

phases.install.cmds = [
  "python3 -m ensurepip",  # ensures pip is installed
  "python3 -m pip install --upgrade pip",
  "python3 -m pip install -r requirements.txt"
]

phases.start.cmd = "cd pharmacy && python3 manage.py runserver 0.0.0.0:$PORT"
