[build]
builder = "NIXPACKS"

[build.nixpacksPlan]
providers = ["python"]

phases.install.cmds = [
  "pip install --upgrade pip",
  "pip install -r requirements.txt"
]

phases.start.cmd = "cd pharmacy && python3 manage.py runserver 0.0.0.0:$PORT"
