# Generated by Django 5.0 on 2025-07-26 05:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_userprofile'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='user',
            new_name='user_email_7bbb4c_idx',
            old_name='users_email_4b85f2_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_role_3744fd_idx',
            old_name='users_role_0ace22_idx',
        ),
        migrations.RenameIndex(
            model_name='user',
            new_name='user_created_855a50_idx',
            old_name='users_created_6541e9_idx',
        ),
        migrations.AlterModelTable(
            name='user',
            table='user',
        ),
    ]
