import {theme} from './Theme'
import { StyleSheet } from 'react-native';
export const styles = StyleSheet.create({
  container: {
    flex: 1,
    backgroundColor: theme.colors.background,
    // Remove extra padding to avoid white bar at the top
    paddingTop: 0,
  },
  header: {
    backgroundColor: 'transparent', // Remove white bar at the top of header
    paddingHorizontal: theme.spacing.md,
    paddingTop: theme.spacing.md,
    paddingBottom: theme.spacing.md,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  location: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  locationText: {
    fontSize: theme.fontSizes.sm,
    fontWeight: '500',
    color: theme.colors.text,
  },
  locationSubtext: {
    fontSize: theme.fontSizes.xs,
    color: theme.colors.subtext,
  },
  headerIcons: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  notification: {
    position: 'relative',
  },
  notificationBadge: {
    position: 'absolute',
    top: -4,
    right: -4,
    width: 12,
    height: 12,
    backgroundColor: theme.colors.error,
    borderRadius: 6,
  },
  profile: {
    width: 32,
    height: 32,
    backgroundColor: theme.colors.primary,
    borderRadius: 16,
    alignItems: 'center',
    justifyContent: 'center',
    marginLeft: theme.spacing.sm,
  },
  searchContainer: {
    padding: theme.spacing.md,
    position: 'relative',
  },
  searchIcon: {
    position: 'absolute',
    left: 28,
    top: 28,
  },
  searchInput: {
    width: '100%',
    paddingLeft: 40,
    paddingRight: theme.spacing.md,
    paddingVertical: theme.spacing.sm,
    backgroundColor: '#F3F4F6',
    borderRadius: 12,
    fontSize: theme.fontSizes.md,
  },
  section: {
    paddingHorizontal: theme.spacing.md,
    marginBottom: theme.spacing.md,
  },
  sectionTitle: {
    fontSize: theme.fontSizes.lg,
    fontWeight: '700',
    color: theme.colors.text,
    marginBottom: theme.spacing.sm,
  },
  linkText: {
    color: theme.colors.primary,
    fontWeight: '500',
    fontSize: theme.fontSizes.sm,
  },
  quickServicesRow: {
    flexDirection: 'row',
    marginTop: theme.spacing.md,
  },
  serviceButton: {
    alignItems: 'center',
    padding: theme.spacing.sm,
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 4,
    elevation: 2,
    flex: 1,
  },
  serviceIcon: {
    padding: theme.spacing.sm,
    borderRadius: 999,
    marginBottom: theme.spacing.sm,
  },
  serviceText: {
    fontSize: theme.fontSizes.xs,
    color: theme.colors.text,
    textAlign: 'center',
    fontWeight: '500',
  },
  categoriesHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: theme.spacing.sm,
  },
  categoriesRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
  },
  categoryButton: {
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    padding: theme.spacing.md,
    alignItems: 'center',
    justifyContent: 'center',
    flex: 1,
    marginHorizontal: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
    minWidth: 0,
  },
  categoryIcon: {
    width: 48,
    height: 48,
    borderRadius: 24,
    alignItems: 'center',
    justifyContent: 'center',
    marginBottom: theme.spacing.sm,
  },
  categoryIconText: {
    fontSize: 24,
  },
  categoryText: {
    fontSize: theme.fontSizes.sm,
    fontWeight: '500',
    color: theme.colors.text,
    textAlign: 'center',
  },
  pharmacyCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    padding: theme.spacing.md,
    marginBottom: theme.spacing.sm,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  pharmacyHeader: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 4,
  },
  pharmacyName: {
    fontWeight: '600',
    color: theme.colors.text,
    fontSize: theme.fontSizes.md,
  },
  pharmacyRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
  },
  pharmacyRating: {
    marginLeft: 4,
    color: '#FBBF24',
    fontWeight: '500',
  },
  pharmacyFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  pharmacyInfoRow: {
    flexDirection: 'row',
    alignItems: 'center',
    gap: 12,
  },
  pharmacyDistance: {
    color: theme.colors.subtext,
    fontSize: theme.fontSizes.sm,
    marginRight: 12,
  },
  pharmacyOpen: {
    fontSize: theme.fontSizes.sm,
    fontWeight: '500',
  },
  pharmacyActionsRow: {
    flexDirection: 'row',
    gap: 8,
  },
  pharmacyActionButton: {
    backgroundColor: '#F3F4F6',
    borderRadius: 8,
    padding: 8,
    marginLeft: 4,
  },
  featuredProductsRow: {
    flexDirection: 'row',
    flexWrap: 'wrap',
    gap: theme.spacing.sm,
  },
  productCard: {
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    padding: theme.spacing.md,
    flex: 1,
    marginHorizontal: theme.spacing.sm,
    marginBottom: theme.spacing.sm,
    minWidth: 0,
    shadowColor: '#000',
    shadowOpacity: 0.05,
    shadowRadius: 2,
    elevation: 1,
  },
  productImageWrapper: {
    position: 'relative',
    alignItems: 'center',
    marginBottom: theme.spacing.sm,
  },
  productImage: {
    fontSize: 32,
    textAlign: 'center',
  },
  favoriteButton: {
    position: 'absolute',
    top: 0,
    right: 0,
    backgroundColor: theme.colors.white,
    borderRadius: 12,
    padding: 4,
    shadowColor: '#000',
    shadowOpacity: 0.1,
    shadowRadius: 2,
    elevation: 2,
  },
  discountBadge: {
    position: 'absolute',
    top: 0,
    left: 0,
    backgroundColor: '#EF4444',
    borderRadius: 8,
    paddingHorizontal: 6,
    paddingVertical: 2,
  },
  discountText: {
    color: '#fff',
    fontSize: 10,
    fontWeight: 'bold',
  },
  productName: {
    fontWeight: '500',
    color: theme.colors.text,
    fontSize: theme.fontSizes.sm,
    marginBottom: 2,
  },
  productCategory: {
    color: theme.colors.subtext,
    fontSize: theme.fontSizes.xs,
    marginBottom: 2,
  },
  productRatingRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  productRating: {
    marginLeft: 4,
    color: '#FBBF24',
    fontWeight: '500',
    fontSize: theme.fontSizes.xs,
  },
  productPriceRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginBottom: 2,
  },
  productPrice: {
    color: '#16A34A',
    fontWeight: 'bold',
    fontSize: theme.fontSizes.md,
  },
  productOriginalPrice: {
    color: theme.colors.subtext,
    fontSize: theme.fontSizes.xs,
    textDecorationLine: 'line-through',
    marginLeft: 6,
  },
  outOfStock: {
    color: '#EF4444',
    fontSize: theme.fontSizes.xs,
    marginTop: 2,
    fontWeight: '500',
  },
  offerCard: {
    minWidth: 280,
    borderRadius: 16,
    padding: theme.spacing.md,
    marginRight: theme.spacing.sm,
  },
  offerTitle: {
    fontSize: theme.fontSizes.lg,
    fontWeight: '700',
    color: theme.colors.white,
  },
  offerSubtitle: {
    fontSize: theme.fontSizes.sm,
    color: theme.colors.white,
    opacity: 0.9,
    marginBottom: theme.spacing.sm,
  },
  offerFooter: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
  },
  offerCode: {
    backgroundColor: 'rgba(255, 255, 255, 0.2)',
    paddingHorizontal: theme.spacing.sm,
    paddingVertical: 4,
    borderRadius: 999,
    fontSize: theme.fontSizes.xs,
    color: theme.colors.white,
  },
});